app/urls.py
from django.urls import path
from .views import *

urlpatterns=[
	path('investigadores/', InvestigadoresView.as_view(), name='investigadores-list'),
	path('investigador/<int:pk>', InvestigadorDetalleView.as_view(), name="investigador-detalle"),
]

urlpatterns+=[
	# path('publicaciones/', PublicacionesView.as_view(), name='publicaciones-list'),
	path('publicaciones/', PublicacionesView, name='publicaciones-list'),
	path('publicacion/<int:pk>', PublicacionDetalleView.as_view(), name="publicacion-detalle"),
	path('publicaciones/iiep/', PublicacionesIIEP, name='publicaciones-iiep'),
	path('publicacion/iiep/<int:id>', PublicacionIIEPDetalle, name='publicacion-iiep-detalle'),
]

urlpatterns+=[
	path('proyectos/', ProyectosView.as_view(), name='proyectos-list'),
	path('proyecto/<int:pk>', ProyectoDetalleView.as_view(), name="proyecto-detalle"),
	path('proyectos/iiep/', ProyectosIIEP, name='proyectos-iiep'),
	path('proyecto/iiep/<int:id>', ProyectoIIEPDetalle, name='proyecto-iiep-detalle'),
]

urlpatterns+=[
	path('actividades/', ActividadesView.as_view(), name='actividades-list'),
	path('actividad/<int:pk>', ActividadDetalleView.as_view(), name="actividad-detalle"),
	path('actividades/iiep/', ActividadesIIEP, name='actividades-iiep'),
	path('actividad/iiep/<int:id>', ActividadIIEPDetalle, name='actividad-iiep-detalle'),
]

urlpatterns+=[
	path('novedades/', NovedadesView, name='novedades-list'),
	path('novedad/<int:pk>', NovedadDetalleView.as_view(), name="novedad-detalle"),
	path('novedades/iiep', NovedadesIIEP, name='novedades-iiep'),
	path('novedad/iiep/<int:id>', NovedadIIEPDetalle, name="novedad-iiep-detalle"),
]

urlpatterns+=[
	# path('datos/', DatosView.as_view(), name='datos-list'),
	path('datos/', DatosView, name='datos-list'),
	path('dato/<int:pk>', DatoDetalleView.as_view(), name="dato-detalle"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
	path('', HomePageView, name='home'),
	path('institucional/', InstitucionalPageView, name='institucional'),
	path('contacto/', Contacto, name='contacto'),
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='core/login.html'), name='logout'),
]

mesi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls, name='admin'),
	path('', include(('core.urls', 'core'), namespace='core')),
	path('app/', include(('app.urls', 'app'), namespace='app')),
	path('pde/', include(('pde.urls', 'pde'), namespace='pde')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pde/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
	path('in/', in_file, name='in'),
	path('out/', out_file, name='out'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey
from ckeditor.fields import RichTextField

class ModeloBase(models.Model):
	estado = models.BooleanField(default=True)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	fecha_modificacion = models.DateTimeField(auto_now=True)
	usuario_creacion = UserForeignKey(auto_user_add=True, related_name='+')
	usuario_modificacion = UserForeignKey(auto_user=True, related_name='+')

	class Meta:
		abstract=True

class SiteSettings(ModeloBase):
	titulo = models.CharField(max_length=300, default="Titulo del sitio")
	desarrollo = RichTextField(help_text="Descripcion del sitio", default="Descripcion del sitio")

	class Meta:
		verbose_name_plural = "Institucional"

	def __str__(self):
		return 'Configuraciones'

	def get_absolute_url(self):
		return reverse('core:institucional', args=[str(self.id)])

core/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(label="Nombre", required=True, 
		widget=forms.TextInput(
			attrs={'class':'form-control', 'placeholder':'Ingrese el nombre'}
		),
		min_length=5, max_length=100)
	email = forms.EmailField(label="Email", required=True, 
		widget=forms.EmailInput(
			attrs={'class':'form-control', 'placeholder':'Ingrese el email'}
		), 
		min_length=5, max_length=100)
	content = forms.CharField(label="Contenido", required=True, 
		widget=forms.Textarea(
			attrs={'class':'form-control', 'rows':3, 'placeholder':'Escribe el mensaje'}
		), 
		min_length=10, max_length=1000)

core/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.contrib import messages
from django.core.mail import EmailMessage
from app.models import Actividad, Publicacion
from iiep.models import Evento as ActividadIIEP
from .forms import ContactForm
from .models import SiteSettings
from django.db.models import Count

class HomePageView(TemplateView):
	template_name = "core/index.html"

class InstitucionalPageView(TemplateView):
	template_name = "core/institucional.html"

	def get_context_data(self, **kwargs):
		context['configuracion'] = SiteSettings.objects.all()[:1]
		return context

def InstitucionalPageView(request):
	template_name="core/institucional.html"
	configuracion = SiteSettings.objects.all()[:1]
	context = {'configuracion':configuracion}
	return render(request, template_name, context)

def HomePageView(request):
	template_name="core/index.html"
	actividades = ActividadIIEP.objects.using('iiep').all().filter(investigador__id__in=[88, 97, 132, 135, 196, 197]).annotate(dcount=Count('investigador__id'))[:4]
	# actividades = Actividad.objects.all()[:4]
	publicaciones = Publicacion.objects.all()[:3]
	configuracion = SiteSettings.objects.all()[:1]
	context = {'actividades':actividades, 'publicaciones':publicaciones, 'configuracion':configuracion}
	return render(request, template_name, context)

def Contacto(request):
	contact_form = ContactForm
	if request.method == "POST":
		contact_form = ContactForm(data=request.POST)
		if contact_form.is_valid():
			name = request.POST.get('name', '')
			email = request.POST.get('email', '')
			content = request.POST.get('content', '')
			email_body = """\
			    <html>
					<head>
						<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-=1">
						<style type="text/css">
							body {font-family:Calibri,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0)}
							p {margin-top:0; margin-bottom:0;}
							b {color:rgb(63,63,63); font-family:Arial; font-size:small}
							div{color:rgb(63,63,63); font-family:Arial; font-size:small}
							span{color:rgb(128,128,128); font-family:Verdana; font-size:8pt}
							hr{display:inline-block;}
							.justificar{text-align: justify;text-justify: inter-word;}
						</style>
					</head>
					<body dir="ltr">
						<div id="appendonsend"></div>
							<hr tabindex="-1">
						<div>
							<h2>De: %s</h2><br>
							<p>Mensaje: %s</p><br>
							<h5>Email de contacto: %s</h5><br>
						</div>
						<br>
						<div id="Signature">
							<div>
								<div id="divtagdefaultwrapper" >
									<div align="left"><b>Atentamente,</b></div>
									<div align="left"><hr></div>
									<div align="left"><b>Diego Osvaldo Cruz Torrez</b></div>
									<div align="left"><b>Consultor IT</b></div>
									<div align="left"><b><img class="EmojiInsert" alt="" src=""><br></b></div>
									<div align="left">
										<span><a href="https://twitter.com/diegocruztorrez" target="_blank">
											http://www.doctsystems.com.bo/</a><br>
										</span>
									</div>
									<div align="left">
										<span>Topater esq. German Busch #1074</span><br>
									</div>
									<div align="left">
										<span>Tel.: +591 4 6961620</span>
									</div>
									<span></span>
									<div align="left"><span>Cel.: +591 72900865 - +591 79260250</span></div>
									<span></span>
									<div align="left"><span>Bermejo - Bolivia</span></div>
									<div align="left"><br>
										<div align="left">
											<b><span class="justificar">La informacion contenida en este mensaje esta dirigida unicamente para el uso del(los) destinatarios(s) señalados arriba. Si el lector de este mensaje no es la persona a quien el mismo fue dirigido, se le notifica que cualquier envio,  distribucion o copia de esta comunicacion o cualquier parte de su contenido, estan estrictamente prohibidos. Si usted ha recibido esta comunicacion por error,  por favor devuelvala al remitente inmediatamente y elimine el mensaje original asi como cualquier copia del mismo en su sistema de computacion.  Si usted tiene alguna pregunta en relacion con este mensaje, por favor comuniquese con el remitente. Gracias por su ayuda.
											</span></b>
										</div>
									</div>
								</div>
							</div>
						</div>
					</body>
				</html>
			    """ % (name, content, email)
			email = EmailMessage('A new mail from MESi', email_body, to=['mesi-iiep@fce.uba.ar', 'doctsystems@gmail.com'])
			email.content_subtype = "html" # this is the crucial part 
			# email.send()

			try:
				email.send()
				# Todo ok
				return redirect(reverse('core:contacto')+'?ok')
			except:
				# Algo fallo en el envio
				return redirect(reverse('core:contacto')+'?fail')

	return render(request, "core/contact.html", {'form': contact_form})

core/templates/includes/footer.html
{% load static %}

<div class="row footer">
	<div class="container">
		<div class="col-md-12">
			<span>© 2020 MESI, Todos los derechos reservados.</span><br>
			<span>Av. Córdoba 2122 - 2do piso (C1120 AAQ) | Ciudad Autónoma de Buenos Aires | República Argentina | Tel/fax: +54 11 5285-6578</span><br>
			
		</div>
		
	</div>
</div>

core/templates/includes/navbar.html
{% load static %}

  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'core:home' %}"><i class="fa fa-lg fa-home"></i></a></li>
          <li><a href="{% url 'core:institucional' %}">Institucional</a></li>
          <li><a href="{% url 'app:investigadores-list' %}">Integrantes</a></li>
          
          <li>
            <a href="{% url 'app:proyectos-iiep' %}" >Proyectos</a>
                                                   
          </li>
          <li>
            <a  href="{% url 'app:actividades-iiep' %}">Actividades</a>                                 
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Publicaciones</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'app:publicaciones-iiep' %}">Publicaciones IIEP</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'app:publicaciones-list'%}">Publicaciones MESi</a>                                       
          </li>
          <li><a href="{% url 'app:novedades-iiep' %}">Novedades</a></li>
          <li><a href="{% url 'app:datos-list' %}">Datos</a></li>
          <li><a href="{% url 'pde:in' %}">Modelos</a></li>
          <li><a href="{% url 'core:contacto' %}">Contacto</a></li>
        </ul>
      </div>
    </div>
  </div>

core/templates/includes/paginacion.html
{% load static %}
<!-- Menú de paginación -->
{% if is_paginated %}
<div class="row">
  <nav aria-label="Page navigation" class="col-md-12">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endif %}