app/urls.py
from django.urls import path
from .views import *

urlpatterns=[
	path('investigadores/', InvestigadoresView.as_view(), name='investigadores-list'),
	path('investigador/<int:pk>', InvestigadorDetalleView.as_view(), name="investigador-detalle"),
]

urlpatterns+=[
	# path('publicaciones/', PublicacionesView.as_view(), name='publicaciones-list'),
	path('publicaciones/', PublicacionesView, name='publicaciones-list'),
	path('publicacion/<int:pk>', PublicacionDetalleView.as_view(), name="publicacion-detalle"),
	path('publicaciones/iiep/', PublicacionesIIEP, name='publicaciones-iiep'),
	path('publicacion/iiep/<int:id>', PublicacionIIEPDetalle, name='publicacion-iiep-detalle'),
]

urlpatterns+=[
	path('proyectos/', ProyectosView.as_view(), name='proyectos-list'),
	path('proyecto/<int:pk>', ProyectoDetalleView.as_view(), name="proyecto-detalle"),
	path('proyectos/iiep/', ProyectosIIEP, name='proyectos-iiep'),
	path('proyecto/iiep/<int:id>', ProyectoIIEPDetalle, name='proyecto-iiep-detalle'),
]

urlpatterns+=[
	path('actividades/', ActividadesView.as_view(), name='actividades-list'),
	path('actividad/<int:pk>', ActividadDetalleView.as_view(), name="actividad-detalle"),
	path('actividades/iiep/', ActividadesIIEP, name='actividades-iiep'),
	path('actividad/iiep/<int:id>', ActividadIIEPDetalle, name='actividad-iiep-detalle'),
]

urlpatterns+=[
	path('novedades/', NovedadesView, name='novedades-list'),
	path('novedad/<int:pk>', NovedadDetalleView.as_view(), name="novedad-detalle"),
	path('novedades/iiep', NovedadesIIEP, name='novedades-iiep'),
	path('novedad/iiep/<int:id>', NovedadIIEPDetalle, name="novedad-iiep-detalle"),
]

urlpatterns+=[
	# path('datos/', DatosView.as_view(), name='datos-list'),
	path('datos/', DatosView, name='datos-list'),
	path('dato/<int:pk>', DatoDetalleView.as_view(), name="dato-detalle"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
	path('', HomePageView, name='home'),
	path('institucional/', InstitucionalPageView, name='institucional'),
	path('contacto/', Contacto, name='contacto'),
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='core/login.html'), name='logout'),
]

mesi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls, name='admin'),
	path('', include(('core.urls', 'core'), namespace='core')),
	path('app/', include(('app.urls', 'app'), namespace='app')),
	path('pde/', include(('pde.urls', 'pde'), namespace='pde')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pde/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
	path('in/', in_file, name='in'),
	path('out/', out_file, name='out'),
]

pde/models.py
from django.db import models

# Create your models here.
class RegMIP(models.Model):
	nacional=models.FileField(upload_to="uploads/files/in/")
	regional=models.FileField(upload_to="uploads/files/in/")
	sector=models.FileField(upload_to="uploads/files/in/")

	class Meta:
		verbose_name_plural = "Archivos"

	def __str__(self):
		return '{}'.format(self.id)

class VideoTutorial(models.Model):
	titulo=models.CharField(max_length=50, help_text="Titulo del video")
	link=models.URLField(max_length = 200, help_text="Link del video")
	tutorial=models.FileField(upload_to="publicaciones/tutoriales/", null=True, blank=True)

	class Meta:
		verbose_name_plural="Tutorial"

	def __str__(self):
		return '{}'.format(self.titulo)

pde/forms.py
from django import forms
from .models import *

class RegMIPForm(forms.ModelForm):

	class Meta:
		model = RegMIP
		fields = ('nacional', 'regional', 'sector')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
				})

pde/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import VideoTutorial
from .forms import RegMIPForm
# from .upfiles import main
from .test2metodos import main

def in_file(request):
	error = False
	files=[]
	if request.method == 'POST':
		form = RegMIPForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			try:
				files=main(post.nacional.url, post.regional.url, post.sector.url)
			except ValueError as e:
				error = True
				context = VideoTutorial.objects.all()[:1]
				return render(request, 'pde/in.html', {'form': form, 'error': error, 'msj': e, 'context': context})
			# return HttpResponseRedirect(reverse('pde:out'))
			return render(request, 'pde/out.html', {'files': files})
	else:
		form = RegMIPForm()
		context = VideoTutorial.objects.all()[:1]
	return render(request, 'pde/in.html', {'form': form, 'context': context})

def out_file(request, id=None):
	return render(request, 'pde/out.html')

pde/templates/pde/in.html
{% extends "base.html" %}
{% load static %}

{% block css_extra %}
<style type="text/css">
    .fileUpload {
    position: relative;
    overflow: hidden;
    margin: 10px;
    }
    .fileUpload input.upload {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        padding: 0;
        font-size: 20px;
        cursor: pointer;
        opacity: 0;
        filter: alpha(opacity=0);
    }
</style>
{% endblock %}

{% block title %} MESI - Matrices {% endblock %}

{% block content %}

<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li class="active">Modelos</li>
</ol>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row">
        <div class="col-sm-6 col-md-6">
            {% if error %}
                <div class="alert alert-danger alert-dismissible show" role="alert">
                    <strong>Error!</strong> {{msj}}.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <h3>Regional I-O MATRIX</h3><hr><br>
            <form enctype="multipart/form-data" action="" method="POST" class="post-form">
                {% csrf_token %}
                <p><label for="id_nacional">National I-O Matrix:</label>
                    <input type="file" name="nacional" class="form-control" required id="id_nacional">
                </p>
                <p><label for="id_regional">Regional GPV:</label>
                    <input type="file" name="regional" class="form-control" required id="id_regional">
                </p>
                <p><label for="id_sector">Sectors Matching for Aggregation:</label>
                    <input type="file" name="sector" class="form-control" required id="id_sector">
                </p>
                <br>
                <input type="submit" class="btn btn-primary btn-block py-2" value="Calculate Regional I-O Matrix">
            </form>
        </div>
        <div class="col-sm-6 col-md-6">
            <h3>Tutorial</h3><hr><br>
            {% if context %}
                {% for conf in context %}
                    <!-- <h4>{{ conf.titulo }}</h4> -->
                    {% if conf.link %}
                        <iframe width="560" height="315" 
                        src="https://www.youtube.com/embed/{{conf.link|slice:'-11:'}}"
                        frameborder="0" allowfullscreen></iframe>
                        <!-- <video name='video' controls autoplay >
                            <source src="{{ conf.link }}" type="video/mp4"></source>
                        </video> -->
                    {% endif %}
                    {% if conf.tutorial %}
                        <p>
                            <a target="_blank" class="btn btn-default" role="button" href="{{ conf.tutorial.url }}">
                            </i> Descargar tutorial en pdf</a>
                        </p>
                    {% endif %}
                {% endfor %}
            {% endif %}
           
        </div>
    </div>
    <div class="well">
        <p>González, S. N., Romero, C. A., Negri, P. A., Ramos, M. P., & Marino, M. (2020). Regional Input-Output Tables Estimation through Indirect Methods: Software and the Buenos Aires province application case. IIEP (UBA-CONICET) - Workshop "Bioenergía y Desarrollo Regional", Noviembre.
        </p>
    </div>
</div>
{% endblock %}
        

pde/templates/pde/out.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESI - Matrices {% endblock %}

{% block content %}

<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'pde:in' %}">Modelos</a></li>
	<li class="active">Formulario de resultados</li>
</ol>

<h1>Regional I-O MATRIX - Results</h1>
<hr>

<div class="page-content row">
	<div class="col-12" >
		{% for file in files %}
			<p>
				<strong>Archivo {{file|slice:":-5"}} </strong>
				<a target="_blank" class="btn btn-default" role="button" href="/media/downloads/files/out/{{file}}">
					<i class="glyphicon glyphicon-download-alt"></i> Descargar archivo
				</a>
			</p>
		{% endfor %}
	</div>
</div>

{% endblock %}