app/urls.py
from django.urls import path
from .views import *

urlpatterns=[
	path('investigadores/', InvestigadoresView.as_view(), name='investigadores-list'),
	path('investigador/<int:pk>', InvestigadorDetalleView.as_view(), name="investigador-detalle"),
]

urlpatterns+=[
	# path('publicaciones/', PublicacionesView.as_view(), name='publicaciones-list'),
	path('publicaciones/', PublicacionesView, name='publicaciones-list'),
	path('publicacion/<int:pk>', PublicacionDetalleView.as_view(), name="publicacion-detalle"),
	path('publicaciones/iiep/', PublicacionesIIEP, name='publicaciones-iiep'),
	path('publicacion/iiep/<int:id>', PublicacionIIEPDetalle, name='publicacion-iiep-detalle'),
]

urlpatterns+=[
	path('proyectos/', ProyectosView.as_view(), name='proyectos-list'),
	path('proyecto/<int:pk>', ProyectoDetalleView.as_view(), name="proyecto-detalle"),
	path('proyectos/iiep/', ProyectosIIEP, name='proyectos-iiep'),
	path('proyecto/iiep/<int:id>', ProyectoIIEPDetalle, name='proyecto-iiep-detalle'),
]

urlpatterns+=[
	path('actividades/', ActividadesView.as_view(), name='actividades-list'),
	path('actividad/<int:pk>', ActividadDetalleView.as_view(), name="actividad-detalle"),
	path('actividades/iiep/', ActividadesIIEP, name='actividades-iiep'),
	path('actividad/iiep/<int:id>', ActividadIIEPDetalle, name='actividad-iiep-detalle'),
]

urlpatterns+=[
	path('novedades/', NovedadesView, name='novedades-list'),
	path('novedad/<int:pk>', NovedadDetalleView.as_view(), name="novedad-detalle"),
	path('novedades/iiep', NovedadesIIEP, name='novedades-iiep'),
	path('novedad/iiep/<int:id>', NovedadIIEPDetalle, name="novedad-iiep-detalle"),
]

urlpatterns+=[
	# path('datos/', DatosView.as_view(), name='datos-list'),
	path('datos/', DatosView, name='datos-list'),
	path('dato/<int:pk>', DatoDetalleView.as_view(), name="dato-detalle"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
	path('', HomePageView, name='home'),
	path('institucional/', InstitucionalPageView, name='institucional'),
	path('contacto/', Contacto, name='contacto'),
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='core/login.html'), name='logout'),
]

mesi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls, name='admin'),
	path('', include(('core.urls', 'core'), namespace='core')),
	path('app/', include(('app.urls', 'app'), namespace='app')),
	path('pde/', include(('pde.urls', 'pde'), namespace='pde')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from core.models import ModeloBase
from stdimage import StdImageField
from django.urls import reverse
from ckeditor.fields import RichTextField

class Investigador(ModeloBase):
	tipos=(
		('nn', '----------'),
		('inv', 'Investigador/a'),
		('aso', 'Asociado/a'),
		('bec', 'Becario/a'),
		('aux', 'Auxiliar'),
		('otr', 'Otro/a'),
	)
	tipo = models.CharField(max_length=3, choices=tipos, default='nn')
	nombres = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	perfil = models.CharField(max_length=100)
	email = models.EmailField(max_length=254, default="email@example.com")
	biografia = RichTextField(help_text="Biografia")
	avatar = StdImageField(upload_to='investigadores/img/avatar/',
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)
	curriculum = models.FileField(upload_to="investigadores/cv/", null=True, blank=True)
	orcid = models.CharField(max_length=30, help_text="Numero ORCID (xxxx-xxxx-xxxx-xxxx)", null=True, blank=True)
	link = models.URLField(max_length = 200, help_text="Link al perfil privado", null=True, blank=True)

	class Meta:
		ordering = ['apellidos', ]
		verbose_name = "integrante"
		verbose_name_plural = "Integrantes"

	def __str__(self):
		return '{}, {}'.format(self.apellidos, self.nombres)

	# def save(self):
	# 	self.nombres=self.nombres.upper()
	# 	self.apellidos=self.apellidos.upper()
	# 	super(Investigador, self).save()

	def get_absolute_url(self):
		return reverse('app:investigador-detalle', args=[str(self.id)])

class Publicacion(ModeloBase):
	tipos=(
		('nn', '----------'),
		('not', 'Notas'),
		('inf', 'Informes Tecnicos'),
		('pub', 'Publicaciones Academicas'),
		('tes', 'Tesis'),
		('otr', 'Otro'),
	)
	categoria = models.CharField(max_length=3, choices=tipos, default='nn')
	titulo = models.CharField(max_length=300, help_text="Titulo de la Publicacion")
	fecha = models.DateField(help_text="Fecha de publicacion")
	cita_APA = RichTextField(help_text="cita_APA", null=True, blank=True)
	resumen_Abstract = RichTextField(help_text="Contenido de la publicacion")
	imagen = StdImageField(upload_to='publicaciones/img/',
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)
	video = models.FileField(upload_to="publicaciones/video/", null=True, blank=True)
	integrantes = models.ManyToManyField(Investigador)
	medios = models.CharField(max_length=100, null=True, blank=True)
	link = models.URLField(max_length=200, null=True, blank=True, help_text="Link al medio")
	doi = models.URLField(max_length=200, null=True, blank=True, help_text="Link DOI")
	es_novedad = models.BooleanField(default=False)

	class Meta:
		ordering = ['-fecha', ]
		verbose_name_plural = "Publicaciones MESI"

	def __str__(self):
		return '{}'.format(self.titulo)

	def get_absolute_url(self):
		return reverse('app:publicacion-detalle', args=[str(self.id)])

class Proyecto(ModeloBase):
	titulo = models.CharField(max_length=300, help_text="Titulo del Proyecto")
	fecha_inicio = models.DateField(help_text="Fecha de inicio")
	fecha_final = models.DateField(help_text="Fecha de finalizacion", null=True, blank=True)
	resumen_Abstract = RichTextField(help_text="Descripcion del proyecto")
	terminado = models.BooleanField(default=False)
	integrantes = models.ManyToManyField(Investigador)

	class Meta:
		verbose_name_plural = "Proyectos"

	def __str__(self):
		return '{}'.format(self.titulo)

	def get_absolute_url(self):
		return reverse('app:proyecto-detalle', args=[str(self.id)])

class Actividad(ModeloBase):
	titulo = models.CharField(max_length=300, help_text="Titulo del evento")
	fecha_inicio = models.DateField(help_text="Fecha de inicio")
	fecha_final = models.DateField(help_text="Fecha de finalizacion", null=True, blank=True)
	hora_inicio = models.TimeField(help_text="Hora de inicio")
	hora_final = models.TimeField(help_text="Hora de finalizacion", null=True, blank=True)
	lugar = models.CharField(max_length=100, help_text="Lugar del evento")
	resumen_Abstract = RichTextField(help_text="Descripcion de la actividad")
	integrantes = models.ManyToManyField(Investigador)
	link = models.URLField(max_length=200, help_text="Formulario de registro", null=True, blank=True)
	logo = StdImageField(upload_to='actividades/logos/',
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)
	flyer = StdImageField(upload_to='actividades/flyers/',
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)

	class Meta:
		verbose_name_plural = "Actividades"

	def __str__(self):
		return '{}'.format(self.titulo)

	def get_absolute_url(self):
		return reverse('app:actividad-detalle', args=[str(self.id)])

class Novedad(ModeloBase):
	titulo = models.CharField(max_length=300)
	fecha = models.DateField(help_text="Fecha de ocurrencia")
	cita_APA = RichTextField(help_text="cita_APA", null=True, blank=True)
	resumen_Abstract = RichTextField(help_text="Descripcion de la novedad")
	imagen = StdImageField(upload_to='novedades/img/', 
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)
	link = models.URLField(max_length = 200, help_text="Link de la presentacion")

	class Meta:
		ordering = ['-fecha', ]
		verbose_name_plural = "Novedades"

	def __str__(self):
		return '{}'.format(self.titulo)

	def get_absolute_url(self):
		return reverse('app:novedad-detalle', args=[str(self.id)])

class Dato(ModeloBase):
	tipos=(
		('nn', '----------'),
		('ene', 'Energia y ambiente'),
		('sec', 'Datos sectoriales'),
		('mat', 'Datos matriciales'),
		('com', 'Comercio'),
		# ('otr', 'Otro'),
	)
	categoria = models.CharField(max_length=3, choices=tipos, default='nn')
	fecha = models.DateField(help_text="Fecha...")
	titulo = models.CharField(max_length=300, help_text="Titulo...")
	cita_APA = RichTextField(help_text="cita_APA", null=True, blank=True)
	resumen_Abstract = RichTextField(help_text="Descripcion...")
	imagen = StdImageField(upload_to='datos/img/', 
		variations={'thumbnail': {"width": 240, "height": 200, "crop": True}},
		null=True, blank=True)
	integrantes = models.ManyToManyField(Investigador)

	class Meta:
		ordering = ['-fecha', ]
		verbose_name_plural = "Datos y Estadisticas"

	def __str__(self):
		return '{}'.format(self.titulo)

	def get_absolute_url(self):
		return reverse('app:dato-detalle', args=[str(self.id)])

class Archivo(ModeloBase):
	publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, null=True, blank=True)
	proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, null=True, blank=True)
	actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE, null=True, blank=True)
	novedad = models.ForeignKey(Novedad, on_delete=models.CASCADE, null=True, blank=True)
	dato = models.ForeignKey(Dato, on_delete=models.CASCADE, null=True, blank=True)
	descripcion = models.CharField(max_length=300, help_text="Titulo o nombre del archivo")
	archivo = models.FileField(upload_to="uploads/files/")

	class Meta:
		verbose_name_plural = "Archivos"

	def __str__(self):
		return '{}'.format(self.id)

app/templates/app/actividad_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESi - Detalles {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'app:actividades-list' %}">Actividades MESi</a></li>
	<li class="active">{{ actividad.fecha_inicio }}</li>
</ol>

<h1>{{ actividad.titulo }}</h1>
<hr>

<div class="page-content row">
	<div class="col-12" >
		<div class="col-md-4">
			<div class="image-content-detail">
			{% if actividad.logo %}
				<a href="{{ actividad.logo.url }}" target="_blank"><img alt="" src="{{ actividad.logo.url }}" class="card-img-top mx-auto img-thumbnail"/></a>
			{% else %}
				<img src="/media/publicaciones/img/nn.png" alt="" class="card-img-top img-thumbnail">
			{% endif %}
			</div>
		</div>
		<div class="actividades col-md-12 card">
			<span class="fecha"><b>Fecha y hora del evento: </b>
				{{actividad.fecha_inicio|date:'d-m-Y' }}  {{actividad.hora_inicio}}
			</span>
			<div class="atividad-name-home">
				<b>Lugar del evento: </b>{{actividad.lugar}}<br>
				<span aria-hidden="true"><br><b>Descripcion: </b>
					{{actividad.resumen_Abstract|safe}}
				</span>
			</div>
			{% if actividad.link %}
				<b>Link de registro: </b>{{actividad.link}}<br>
			{% endif %}
		</div>
		<div class="image-content-detail">
			<b>Flyer del evento: </b><br>
			{% if actividad.flyer %}
				<a href="{{ actividad.flyer.url }}" target="_blank"><img 
					src="{{ actividad.flyer.url }}" class="card-img-top mx-auto img-thumbnail"/>
				</a>
			{% else %}
				<img src="/media/publicaciones/img/nn.png" alt="" class="card-img-top img-thumbnail">
			{% endif %}
			</div>
	</div>
</div>
{% endblock %}

app/templates/app/actividad_detail_iiep.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESI - Actividad IIEP {% endblock %}

{% block content %}
 <ol class="breadcrumb">
    <li><a href="{% url 'core:home' %}">Inicio</a></li>
    <li><a href="{% url 'app:actividades-iiep' %}">Actividades IIEP</a></li>
	<li class="active">{{evento.titulo_espanol|safe}}</li>
  </ol>

<hr>

<div class="page-content row">
    <div class="col-12" >
        <div class="col-md-8 col-md-offset-2 " >
            <h2 style="color: green;">{{evento.titulo_espanol|safe}}</h2>
            <p>{{evento.texto_espanol|safe}}</p>
        </div>
        
    </div>

</div>
{% endblock %}

app/templates/app/actividades_iiep.html
{% extends "base.html" %}
{% load static %}
{% load timetags %}

{% block title %} MESi - Actividades MESi  {% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Inicio</a></li>
  <li class="active">Actividades MESi </li>
</ol>
<h1>Actividades  MESi </h1>
<hr>

<div class="page-content row">
	<div class="col-md-12">
  {% if eventos %}
		{% for evento in eventos %}
      <div class="col-md-7 col-md-offset-2" style="margin-bottom: 5px;">
        <h2><a href="{{ evento.get_absolute_url }}">{{evento.titulo_espanol}}</a> </h2>	
        <h4>{{evento.fecha|timestamp_to_date}}<br>
       
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span> {{evento.hora}} Hs.<br>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> {{evento.lugar}} </h4>
            
        <h4 style="display: none;">Del <b>{{evento.fecha|timestamp_to_date}}</b> al 
          {% if evento.fecha_hasta %}
            <b>{{evento.fecha_hasta|timestamp_to_date}}</b>
          {% else %}
            <b>{{evento.fecha|timestamp_to_date}}</b>
          {% endif %}
        </h4>
			
				<!-- <p>{{evento.texto_espanol|striptags|safe|truncatechars:"300"}}</p> -->
        <p>{{evento.texto_espanol|safe}}</p>
        
        <hr>
			</div>
		{% endfor %}
  {% endif %}
  </div>
</div>

<div class="row">
 <div class="col-md-12">
        {% if eventos.has_other_pages %}
      <ul class="pagination">
        {% if eventos.has_previous %}
          <li><a href="?page={{ eventos.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in eventos.paginator.page_range %}
          {% if eventos.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if eventos.has_next %}
          <li><a href="?page={{ eventos.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
</div>
</div>
{% endblock %}

app/templates/app/actividades_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESi - Actividades {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li class="active">Actividades</li>
</ol>
<h1>Actividades MESi</h1>
<hr>

<div class="page-content">
	<div class="col-md-12">
		{% if actividad_list %}
			{% for actividad in actividad_list %}
			<div class="media">
					
					<div class="img col-md-2">
					{% if actividad.flyer %}
					<a href="{{ actividad.flyer.url }}" target="_blank"><img 
						src="{{ actividad.flyer.url }}" class="media-object img-responsive" />
					</a>
				{% else %}
					<img src="/media/publicaciones/img/nn.png" alt="" class="media-object img-responsive">
				{% endif %}	
			</div>				
			<div class="media-body">
			
					<h4><a href="{{ actividad.get_absolute_url }}">{{actividad.titulo}}</a></h4>
				
						<strong>{{actividad.fecha_inicio|date:'Y-m-d' }} - {{actividad.hora_inicio}}</strong>
					
					<strong>
						<span>{{actividad.lugar}} </span></strong><br>
						<span aria-hidden="true">
							{{actividad.desarrollo|striptags|safe|truncatechars:"300"}}
						</span><br>             
					</div>
					<hr>
				</div>
			{% endfor %}
		{% else %}
			<div class="alert alert-info">No existen actividades...</div>
		{% endif %}
	</div>
</div>
{% endblock %}

app/templates/app/datos_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESi - Datos {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li class="active">Datos y Estadísticas</li>
</ol>
<h1>Datos y Estadísticas - MESi</h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#energia" aria-controls="energia" role="tab" data-toggle="tab">Energía y Ambiente</a></li>
	<li role="presentation"><a href="#sectoriales" aria-controls="sectoriales" role="tab" data-toggle="tab">Datos Sectoriales</a></li>
	<li role="presentation"><a href="#matriciales" aria-controls="matriciales" role="tab" data-toggle="tab">Datos Matriciales</a></li>
	<li role="presentation"><a href="#comercio" aria-controls="comercio" role="tab" data-toggle="tab">Comercio</a></li>

</ul>

<div class="tab-content">
	<div role="tabpanel" class="tab-pane active" id="energia" style="padding-top:15px;">
		{% include 'includes/datos/energia.html' %}
	</div>
	<div role="tabpanel" class="tab-pane" id="sectoriales" style="padding-top:15px;">
		{% include 'includes/datos/sectoriales.html' %}
	</div>
	<div role="tabpanel" class="tab-pane" id="matriciales" style="padding-top:15px;">
		{% include 'includes/datos/matriciales.html' %}
	</div>
	<div role="tabpanel" class="tab-pane" id="comercio" style="padding-top:15px;">
		{% include 'includes/datos/comercio.html' %}
	</div>
</div>
{% endblock %}

app/templates/app/investigador_detail.html
{% extends "base.html" %}
{% load static %}

{% block css_extra %}
<style type="text/css">
	body { 
		padding-top:30px;
	}
	.glyphicon {
		margin-bottom: 10px;margin-right: 10px;
	}
	small {
		display: block;
		line-height: 1.428571429;
		color: #999;
	}
</style>
{% endblock %}

{% block title %} MESi - Detalles {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'app:investigadores-list' %}">Integrantes MESi</a></li>
	<li class="active">{{ investigador }}</li>
</ol>
<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            {% if investigador.avatar %}
				<img src="{{ investigador.avatar.url }}" alt="Avatar" 
                style="border-radius: 50%; width: 100%;">
			{% else %}
				<img src="/media/investigadores/img/avatar/male.png" alt="Avatar" class="img-responsive">
			{% endif %}
        </div>
        <div class="col-sm-9 col-md-9 well">
            <h4><b>{{ investigador }}</b></h4>
            <small>
            	<cite title="Buenos Aires, ARG">Buenos Aires, ARG 
            		<i class="glyphicon glyphicon-map-marker"></i>
            	</cite>
            </small>
            <p>
            	<i class="glyphicon glyphicon-info-sign"></i>{{investigador.get_tipo_display}}<br/>
                <i class="glyphicon glyphicon-envelope"></i>{{investigador.email}}<br/>
                {% if investigador.link %}
                    <i class="glyphicon glyphicon-globe"></i>
                    <a href="{{ investigador.link }}" target="_blank">{{investigador.link}}</a><br/>
                {% endif %}
                {% if investigador.orcid %}
                    <i class="glyphicon glyphicon-cloud"></i>
                    <a href="https://orcid.org/{{ investigador.orcid }}" target="_blank">
                        Visita mi página de Orcid
                    </a><br>
                {% endif %}
                {% if investigador.curriculum %}
                    <i class="glyphicon glyphicon-file"></i>
                    <a href="{{ investigador.curriculum.url }}" target="_blank">Mi curriculum</a><br/>
                {% endif %}
            </p>
            <h4>Perfil</h4>
            <p>{{investigador.perfil|safe}}</p>
            <h4>Biografía</h4>
            <p>{{investigador.biografia|safe}}</p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/novedad_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESi - Detalles {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'app:novedades-list' %}">Novedades MESi</a></li>
	<li class="active">{{ novedad.titulo }}</li>
</ol>

<h1>{{ novedad.titulo }}</h1>
<hr>

<div class="page-content row">
	<div class="col-12" >
		<div class="col-md-4">
			<div class="image-content-detail">
				{% if publicacion.imagen %}
					<a href="{{ publicacion.imagen.url }}"><img alt="" src="{{ publicacion.imagen.url }}" class="card-img-top img-thumbnail"/></a>
				{% else %}
					<img src="/media/publicaciones/img/nn.png" alt="" class="card-img-top img-thumbnail">
				{% endif %}
			</div>
		</div>
		<div class="col-md-8 fecha-publicacion">
			<p><strong>Fecha: {{ novedad.fecha }}</strong></p>
			<p><strong>Link: </strong><a href="{{ novedad.link }}" target="_blank">{{ novedad.link }}</a></p>
			<p><strong>Cita APA: </strong>{{ novedad.copete|safe }}</p>
			<p><strong>Resumen/Abstract: </strong>{{ novedad.desarrollo|safe }}</p>
		</div>
	</div>
</div>
{% endblock %}

app/templates/app/proyecto_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESi - Detalles {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'app:proyectos-list' %}">Proyectos MESi</a></li>
	<li class="active">{{ proyecto.titulo }}</li>
</ol>

<h1>{{ proyecto.titulo }}</h1>
<hr>

<div class="page-content row">
	<div class="col-12" >
		<div class="col-md-4">
			<p><strong>Fecha de Inicio: </strong>{{ proyecto.fecha_inicio }}</p>
			<p>
				{% if proyecto.fecha_final %}
					<strong>Archivos: </strong>
					{{ proyecto.fecha_final }}
				{% endif %}
			</p>
			<p><strong>Autor/es: </strong>
				{% for autor in proyecto.integrantes.all %}
					<span>{{ autor }},</span>
				{% endfor %}
			</p>
		</div>
		<div class="col-md-8 fecha-proyecto">
			
			<p><strong>Cita APA: </strong>{{ proyecto.copete|safe }}</p>
			<p><strong>Resumen/Abstract: </strong>{{ proyecto.desarrollo|safe }}</p>
			<p><strong>Archivos: </strong>
				{% for file in proyecto.archivo_set.all %}
					<a target="_blank" class="btn btn-default" role="button" href="{{ file.archivo.url }}">
						<i class="glyphicon glyphicon-download-alt"></i> Descargar archivo
					</a>
				{% endfor %}
			</p>
		</div>
	</div>
</div>
{% endblock %}

app/templates/app/proyecto_detail_iiep.html
{% extends "base.html" %}
{% load static %}

{% block title %} MESI - Proyecto {% endblock %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url 'core:home' %}">Inicio</a></li>
	<li><a href="{% url 'app:proyectos-iiep' %}">Proyectos IIEP</a></li>
	<li class="active">{{ proyecto.titulo_espanol }}</li>
</ol>
 <hr>

<div class="row">

    <div class="col-md-8 col-md-offset-2 " >
        <h2 style="color: green;">{{proyecto.titulo_espanol}}</h2>
        <p>{{proyecto.descripcion_espanol|safe}}</p> </div>
        
    <div class="col-md-12 " style="display: none;">
        <a class="btn btn-default" role="button" target="_blank" href="http://iiep-baires.econ.uba.ar/uploads/publicaciones/{{proyecto.id}}/archivos/1.pdf"><i class="glyphicon glyphicon-download-alt"></i>  Descargar archivo</a>

    </div>
</div>
{% endblock %}

app/templates/app/publicacion_detail_iiep.html
{% extends "base.html" %}
{% load static %}
{% load timetags %}

{% block title %} MESi - Publicacion IIEP {% endblock %}

{% block content %}
<ol class="breadcrumb">
    <li><a href="{% url 'core:home' %}">Inicio</a></li>
    <li><a href="{% url 'app:publicaciones-iiep' %}">Publicaciones IIEP</a></li>

	<li class="active">{{publicacion.titulo_espanol}}</li>
  </ol>
  <h1>{{publicacion.titulo_espanol}}</h1>
<hr>

<div class="page-content row">
<div class="col-12" >

    <div class="col-md-4">
        <img style="width: 100%;" src="http://iiep-baires.econ.uba.ar/uploads/publicaciones/{{publicacion.id}}/imagenes/1_ficha.jpg" alt="">
       
    </div>

    <div class="col-md-8 fecha-publicacion">
      
        <p> <strong>{{publicacion.fecha|timestamp_to_date}}</strong></p>
        <p>{{publicacion.texto_espanol|safe}}</p>

        <p>
        <a target="_blank" class="btn btn-default" role="button" href="http://iiep-baires.econ.uba.ar/uploads/publicaciones/{{publicacion.id}}/archivos/1.pdf"><i class="glyphicon glyphicon-download-alt"></i> Descargar archivo</a></p>
    </div>
    
</div>

</div>

{% endblock %}